spring:
  profiles:
    active:
      - qa #activate qa profile
    config:
      import:
        - "application-qa.yml"
        - "application-prod.yml"
  datasource:
    url: jdbc:h2:mem:cards
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  console:
    enabled: true
    path: /h2-console
  application:
    name: cards
  #  datasource:
  #    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/cards
  #    password: ${MYSQL_PASSWORD:0987}
  #    username: ${MYSQL_USER:root}
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  version: "v1"

server:
  port: 8082

contact:
  author: David Bakare
  profile: default
  service: cards
  url: https://github.com/3akare/Microservices-with-Spring-Boot