spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8084/
  cloud:
    gateway:
      actuator:
        verbose:
          enabled: true
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
info:
  app:
    name: gatewayserver
    description: 3ank gatewayserver application
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true