#spring: (this file can be deleted)
#  config:
#    on-active: "prod"
#
#contact:
#  author: David Bakare
#  profile: prod
#  service: loans
#  url: https://github.com/3akare/Microservices-with-Spring-Boot