spring:
  profiles:
    active:
      - "qa" #activate qa profile
  datasource:
    url: jdbc:h2:mem:loans
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  console:
    enabled: true
    path: /h2-console
  application:
    name: loans
  #  datasource:
  #    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/loans
  #    password: ${MYSQL_PASSWORD:0987}
  #    username: ${MYSQL_USER:root}
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083