spring:
  application:
    name: eurekaserver
  config:
    import: optional:configserver:http://localhost:8084/

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:  # check the readiness and liveness of the config server using actuator health. This helps ensure that the server is alive and ready to be used
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
