version: '3.7'

services:
  # Eureka server
  eurekaserver:
    image: 3akare/eurekaserver:v4
    container_name: eurekaserver-ms
    ports:
      - 8085:8085
    healthcheck:
      test: "curl --fail --silent localhost:8085/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: eurekaserver

  # Config Server
  configserver:
    image: 3akare/configserver:v4
    container_name: configserver-ms
    ports:
      - 8084:8084
    healthcheck:
      test: "curl --fail --silent localhost:8084/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  # Accounts Microservice
  accounts:
    image: 3akare/accounts:v4
    container_name: accounts-ms
    ports:
      - 8081:8081
    environment:
      SPRING_APPLICATION_NAME: accounts
    extends:
      file: common-config.yml
      service:  microservice-eureka-config

  # Cards Microservice
  cards:
    image: 3akare/cards:v4
    container_name: cards-ms
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_NAME: cards
    extends:
      file: common-config.yml
      service:  microservice-eureka-config

  # Loans Microservice
  loans:
    image: 3akare/loans:v4
    container_name: loans-ms
    ports:
      - 8083:8083
    environment:
      SPRING_APPLICATION_NAME: loans
    extends:
      file: common-config.yml
      service:  microservice-eureka-config

networks:
  bank-ms:
    driver: bridge
