version: '3.7'

services:
  accountsdb:
    container_name: accountsdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    container_name: cardsdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    container_name: loansdb
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  # Config Server
  configserver:
    image: 3akare/configserver:v3
    container_name: configserver-ms
    ports:
      - 8084:8084
    healthcheck:
      test: "curl --fail --silent localhost:8084/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  # Accounts Microservice
  accounts:
    image: 3akare/accounts:v3
    container_name: accounts-ms
    ports:
      - 8081:8081
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_DATASOURCE_URL: jdbc:mysql://accountsdb:3306/accountsdb
    depends_on:
      accountsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service:  microservice-configserver-config

  # Cards Microservice
  cards:
    image: 3akare/cards:v3
    container_name: cards-ms
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_DATASOURCE_URL: jdbc:mysql://cardsdb:3306/cardsdb
    depends_on:
      cardsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service:  microservice-configserver-config

  # Loans Microservice
  loans:
    image: 3akare/loans:v3
    container_name: loans-ms
    ports:
      - 8083:8083
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_DATASOURCE_URL: jdbc:mysql://loansdb:3306/loansdb
    depends_on:
      loansdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service:  microservice-configserver-config

networks:
  bank-ms:
    driver: bridge
