spring:
  profiles:
    active:
      - qa #activate qa profile
  datasource:
    url: jdbc:h2:mem:accounts
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  console:
    enabled: true
    path: /h2-console
  application:
    name: accounts
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/accounts
#    password: ${MYSQL_PASSWORD:0987}
#    username: ${MYSQL_USER:root}
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  version: "v1"

server:
  port: 8081

contact:
  author: David Bakare
  profile: default
  service: accounts
  url: https://github.com/3akare/Microservices-with-Spring-Boot