spring:
  application:
    name: configserver
  profiles:
    active: native #save to classpath
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"

server:
  port: 8084