spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          #search-locations: "classpath:/config" #read from classpath
          #search-locations: "file:///User... file path" # read from file system
        search-locations:

server:
  port: 8084