spring:
  application:
    name: configserver
  profiles:
    active: git
    #active: native #from local machine
  cloud:
    config:
      server:
        git:
          uri: https://github.com/3akare/Microservice-Config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
          #search-locations: "classpath:/config" #read from classpath
          #search-locations: "file:///C://Users//DAVID-BAKARE//Documents//Microservice-Config" # read from file system
  rabbitmq:
    host: localhost
    port: 5672
  #    password: guest
  #    username: guest

management:
  endpoints:
    web:
      exposure:
        included: "*"
  health:  # check the readiness and liveness of the config server using actuator health. This helps ensure that the server is aliv and ready to be used
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: OIDJOIEJIDJIFODONEKODNOKENDONEPFOJPJFPIJFBP #to encrypt sensitive data

server:
  port: 8084