services:
  #AMQP
  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service
#======    this is commented out because the required data is extracted from common-config.yml ======
#    networks:
#      - bank-ms

  #configserver
  configserver:
    image: 3akare/configserver:v2
    container_name: configserver-ms
    ports:
      - 8084:8084
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8084/actuator/health/readiness | grep UP || exit 1" # Test the readiness of the configserver
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config
#======    this is commented out because the required data is extracted from common-config.yml ======
#    deploy:
#      resources:
#        limits:
#          memory: 700m # maximum of 700mb memory size
#    networks:
#      - bank-ms this is commented out because the required data is extracted from common-config.yml

  #accounts
  accounts:
    image: 3akare/accounts:v2
    container_name: accounts-ms
    ports:
      - 8081:8081
    environment:
      SPRING_APPLICATION_NAME: accounts #the spring application name. It is important because of a bug
    extends:
      file: common-config.yml
      service:  microservice-configserver-config
#======    this is commented out because the required data is extracted from common-config.yml ======
#      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8084/" # the configserver within the docker network. Make sure isn't optional
#      SPRING_PROFILES_ACTIVE: prod
#    depends_on:
#      configserver:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m # maximum of 700mb memory size
#    networks:
#      - bank-ms
  #cards
  cards:
    image: 3akare/cards:v2
    container_name: cards-ms
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_NAME: cards
    extends:
      file: common-config.yml
      service: microservice-configserver-config
#======    this is commented out because the required data is extracted from common-config.yml ======
#    depends_on:
#      configserver:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - bank-ms
#      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8084/"
#      SPRING_PROFILES_ACTIVE: prod

  #loans
  loans:
    image: 3akare/loans:v2
    container_name: loans-ms
    ports:
      - 8083:8083
    environment:
      SPRING_APPLICATION_NAME: loans
    extends:
      file: common-config.yml
      service: microservice-configserver-config
#======    this is commented out because the required data is extracted from common-config.yml ======
#    depends_on:
#      configserver:
#        condition:
#          service_healthy
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    networks:
#      - bank-ms
#      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8084/"
#      SPRING_PROFILES_ACTIVE: prod

# network
networks:
  bank-ms:
    driver: bridge